name: Update GitHub Activity

on:
  schedule:
    - cron: "0 * * * *" # runs every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "chore: update activity"
          MAX_LINES: 5          # optional: number of activity lines to include
          TARGET_FILE: README.md # optional: where to insert activity
